### ISSUE TITLE
traitsui v7.0.0 not uploaded on anaconda cloud

### ISSUE THREAD

**Issue by ericpre** [conda-forge/traitsui-feedstock#14]
Even if https://github.com/conda-forge/traitsui-feedstock/pull/13 have been merged and CI pass, the package hasn't been uploaded to anaconda cloud: https://anaconda.org/conda-forge/traitsui/files

**Comment by grlee77** [comment]
Thanks. I'm not sure how that happened! I guess we can make a new PR just bumping the build number and rerendering and then merge that and see if it fixes the issue.

**Comment by ericpre** [comment]
Oh well, most likely the infrastructure was not very collaborative that day! Since the packages are not there, simply restarting the CI build from github may work too?

**Comment by ericpre** [comment]
> Oh well, most likely the infrastructure was not very collaborative that day! Since the packages are not there, simply restarting the CI build from github may work too?

Actually, this is not possible, since there is no CI build for the merge commit: https://github.com/conda-forge/traitsui-feedstock/commit/0a9d5dd9106c92142b3187f90cc3aee56e3722cc

**Comment by grlee77** [comment]
I just merged #15 to try and rebuild. Let's see if it shows up on anaconda.org within the next 20-30 minutes

**Comment by grlee77** [comment]
okay, I see it there now: https://anaconda.org/conda-forge/traitsui/files
Thanks for raising the issue. I will do the same for pyface now

**Comment by ericpre** [comment]
Thanks!
